### ISSUE TITLE
Corrección

### ISSUE THREAD

**Issue by gastonprieto** [MartinSchvartz/DDS-MacoWins#1]
* Completar con pseudocódigo, en general sin ese detalle puede que las clases esten ok, pero que los comportamientos esten mal asignados. No se ve por ejemplo como interactuan los objetos entre si (una de las cosas que hacemos al definir el diseño)
* El diagrama lo veo bien

> Se podría implementar la forma de pago en la clase de ventas con un Enum en lugar de con una interfaz?

si, perfecto.

**Comment by MartinSchvartz** [comment]
Genial Gaston, muchas gracias x la corrección.😁
